version: '3.2'
services:
   db:
     image: mysql:5.7
     container_name: Full2020-86442
     restart: always
     environment:
          -MYSQL_ROOT_PASSWORD: wilkiga
          -MYSQL_USER:  IWilk
          -MYSQL_PASSWORD: wilkiga
          -MYSQL_DATABASE: biblioteka
     networks:
          BridgeZadanie1:
             ipv4_address: 10.0.10.3
   phpmyadmin:
      depends_on:
         - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      environment:
         PMA_HOST: db
         MYSQL_PASSWORD: wilkiga
      networks:
         - BridgeZadanie1
      ports:
        - 8080:80
   java:
      container_name: lab4
      depends_on:
          - db
      image: igamagisterskie/laboratorium4:latest
      networks:
          - BridgeZadanie1 
      tty: true
      stdin_open: true

networks:
    BridgeZadanie1:
        driver: bridge
        ipam:
           config:
               - subnet: 10.0.10.0/8
